{
 "title": "Milvus Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "QPM (Query per minute)",
   "type": "graph",
   "description": "Number of queries completed in every minute",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_vector_response_summary_count-(query_vector_response_summary_count offset 1m)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "The time (in minutes) Milvus server has been working and available",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "keeping_alive_seconds_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cache utilization ratio",
   "type": "gauge",
   "description": "Cache utilization ratio(%)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "cache_usage_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "milvus CPU utilization ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "CPU_usage_percent{CPU=\"avg\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    { "expr": "CPU_temperature", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "bargauge",
   "description": "GPU utilization(MB)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "GPU_memory_usage_total", "legendFormat": "{{job}}:gpu{{DeviceNum}}" }
   ]
  },
  {
   "title": "Memory usage ratio",
   "type": "graph",
   "description": "Memory (in GB) currently consumed by Milvus",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "RAM_usage_percent" }
   ]
  },
  {
   "title": "GPU utilization ratio",
   "type": "bargauge",
   "description": "GPU utilization rate(%)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    { "expr": "Gpu_usage_percent", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "GPU temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "targets": [
    { "expr": "GPU_temperature", "legendFormat": "{{job}}:gpu{{GPU}}" }
   ]
  },
  {
   "title": "Query elapsed time",
   "type": "graph",
   "description": "System wide metric. It is the total query elapsed time divided by total number of queries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "query_response_summary/1e6" }
   ]
  },
  {
   "title": "GPU utilization history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "GPU_memory_usage_total" }
   ]
  },
  {
   "title": "Total file",
   "type": "graph",
   "description": "Current number of files in Milvus",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "data_file_size_bytes" }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Network IO read/write speed (per second)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "octets_bytes_per_second" }
   ]
  },
  {
   "title": "Disk write speed",
   "type": "graph",
   "description": "Disk write speed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "disk_store_IO_speed_bytes_per_microseconds*1e6"
    }
   ]
  },
  {
   "title": "Disk read speed",
   "type": "graph",
   "description": "Disk read speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "disk_load_IO_speed_byte_per_microsec*1e6"
    }
   ]
  },
  {
   "title": "Insert per Second",
   "type": "graph",
   "description": "Number of vectors that are inserted in a second.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "add_vectors_throughput_per_microsecond*(1e6)"
    }
   ]
  },
  {
   "title": "Data size",
   "type": "graph",
   "description": "Total amount of data stored in Milvus",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "add_vectors_request_total" }
   ]
  }
 ]
}